
spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411/
  cloud:
    gateway:
      routes:
        - id: CustomerService
          uri: http://localhost:8081/
          predicates:
            - Path=/api/customers/**
        - id: BorrowingService
          uri: lb://BookQueryService
          predicates:
            - Path=/api/borrowing/**
        - id: ReviewService
          uri: http://localhost:8084/
          predicates:
            - Path=/api/reviews/**
        - id: BooksCommandService
          uri: http://localhost:8082/
          predicates:
            - Path=/api/books/**
        - id: BooksQueryService
          uri: http://localhost:8086/
          predicates:
            - Path=/api/bookquerys/**

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

