server:
  port: 8084
spring:
  application:
    name: ReviewService
  zipkin:
    base-url: http://localhost:9411/

  sleuth:
    sampler:
      probability: 1 #100% (default = 10%)

  data:
    mongodb:
      host: localhost
      port: 27017
      database: review

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: gid
      auto-offset-reset: latest
      bootstrap-servers: localhost:9092
      enable-auto-commit: true
      properties:
        spring:
          json:
            trusted:
              packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: localhost:9092
logging:
  level:
    root: ERROR
    org:
      springframework:
        ERROR

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

